services:
  science_db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: science_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 오류 발생시 재실행
    restart: always
    # 실행 전 헬시체크
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - data_science

volumes:
  postgres_data:

# 외부 네트워크 참조
networks:
  data_science:
    external: True

